[package]
name = "day06"
version = "0.1.0"
authors = ["Michael Adler <therisen06@gmail.com>"]
edition = "2018"

[[bin]]
name = "day06"
path = "src/main.rs"

[dependencies]
log = {version = "0.4.0", features = ["release_max_level_warn"]}
env_logger = "0.10"
