[package]
name = "day21"
version = "0.1.0"
authors = ["Michael Adler <therisen06@gmail.com>"]
edition = "2018"

[[bin]]
name = "day21"
path = "src/main.rs"

[dependencies]
aoc2019 = { path = "../share/rust" }
