[package]
name = "day09"
version = "0.1.0"
authors = ["Michael Adler <therisen06@gmail.com>"]
edition = "2018"

[[bin]]
name = "day09"
path = "src/main.rs"

[dependencies]
log = "0.4.0"
env_logger = "0.10"
aoc2019 = { path = "../share/rust" }
